### ISSUE TITLE
Ran smoothly for a while and suddenly got an error and can run anymore

### ISSUE THREAD

**Issue by Samuel-3s** [GuilleDiazFentanes/AutoClaim-AutoRoll-AutoReact-MudaeBot-2024#27]
Everything was smooth and I never changed any setting, ID, password, ch ID, etc, nothing but this crash pops in and I have no idea of it.

Here below is the error log. I have running 2 bots and the same machine, bot have the same error.

```Rolling at 16:15 - 25/06/24
Traceback (most recent call last):
  File "/mnt/user/appdata/AutoClaim-AutoRoll-AutoReact-MudaeBot-2024/xxx/Bot.py", line 10, in <module>
    schedule.run_pending()
  File "/usr/lib64/python3.9/site-packages/schedule/__init__.py", line 854, in run_pending
    default_scheduler.run_pending()
  File "/usr/lib64/python3.9/site-packages/schedule/__init__.py", line 101, in run_pending
    self._run_job(job)
  File "/usr/lib64/python3.9/site-packages/schedule/__init__.py", line 173, in _run_job
    ret = job.run()
  File "/usr/lib64/python3.9/site-packages/schedule/__init__.py", line 691, in run
    ret = self.job_func()
  File "/mnt/user/appdata/AutoClaim-AutoRoll-AutoReact-MudaeBot-2024/xxx/Function.py", line 21, in simpleRoll
    rollCommand = SlashCommander(bot.getSlashCommands(botID).json()).get([Vars.rollCommand])
  File "/usr/lib64/python3.9/site-packages/discum/utils/slash.py", line 84, in get
    current_cmd = next(
  File "/usr/lib64/python3.9/site-packages/discum/utils/slash.py", line 87, in <genexpr>
    if c["name"] == cmd and c["type"] in (1, 2)
KeyError: 'name'
```

```Rolling at 16:30 - 25/06/24
Traceback (most recent call last):
  File "/mnt/user/appdata/AutoClaim-AutoRoll-AutoReact-MudaeBot-2024/yyy/Bot.py", line 10, in <module>
    schedule.run_pending()
  File "/usr/lib64/python3.9/site-packages/schedule/__init__.py", line 854, in run_pending
    default_scheduler.run_pending()
  File "/usr/lib64/python3.9/site-packages/schedule/__init__.py", line 101, in run_pending
    self._run_job(job)
  File "/usr/lib64/python3.9/site-packages/schedule/__init__.py", line 173, in _run_job
    ret = job.run()
  File "/usr/lib64/python3.9/site-packages/schedule/__init__.py", line 691, in run
    ret = self.job_func()
  File "/mnt/user/appdata/AutoClaim-AutoRoll-AutoReact-MudaeBot-2024/yyy/Function.py", line 21, in simpleRoll
    rollCommand = SlashCommander(bot.getSlashCommands(botID).json()).get([Vars.rollCommand])
  File "/usr/lib64/python3.9/site-packages/discum/utils/slash.py", line 84, in get
    current_cmd = next(
  File "/usr/lib64/python3.9/site-packages/discum/utils/slash.py", line 87, in <genexpr>
    if c["name"] == cmd and c["type"] in (1, 2)
KeyError: 'name'
```

let me know if you need anymore infos.

**Comment by Samuel-3s** [comment]
Update:
Found out my Discord token is outdated, even though I didn't change my password or what, updated the token and it is fine right now.

Thank! Looking forward to the advanced model!
