### ISSUE TITLE
Bot stops when $bku drops

### ISSUE THREAD

**Issue by Furgoder** [GuilleDiazFentanes/AutoClaim-AutoRoll-AutoReact-MudaeBot-2024#4]
Hello.
I hope you're doing well. I wanted to bring up an issue I've encountered with the bot. It seems that the bot is having trouble handling the case when a card with a percentage chance, such as 'bku', is rolled. This appears to be causing a template mismatch error and is preventing the bot from functioning correctly in such cases.
![image](https://github.com/GuilleDiazFentanes/AutoClaim-AutoRoll-AutoReact-MudaeBot-2024/assets/81800846/574b4ef7-f40c-49d9-bd4a-69650fe1e972)
Here the console log:
Trying to roll Pokeslot
Rolling at 19:41 - 08/01/24
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\AutoClaim-AutoRoll-AutoReact-MudaeBot-2023-main\Bot.py", line 10, in <module>
    schedule.run_pending()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\schedule\__init__.py", line 822, in run_pending
    default_scheduler.run_pending()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\schedule\__init__.py", line 100, in run_pending
    self._run_job(job)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\schedule\__init__.py", line 172, in _run_job
    ret = job.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\schedule\__init__.py", line 693, in run
    ret = self.job_func()
  File "C:\Users\Administrator\Desktop\AutoClaim-AutoRoll-AutoReact-MudaeBot-2023-main\Function.py", line 39, in simpleRoll
    cardPower = int((jsonCard[0]['embeds'][0]['description']).split('**')[1])
ValueError: invalid literal for int() with base 10: '43.5%'

**Comment by GuilleDiazFentanes** [comment]
It should be fixed now!! It was just a line of code
